-- IAMARAL."reclamacoes_contexto" definition
CREATE TABLE "IAMARAL"."reclamacoes_contexto" 
   (	"DataExtracao" VARCHAR2(50), 
	"SOLICITAÇÕES" NUMBER(*,0), 
	"Ano" NUMBER(*,0), 
	"Mês" NUMBER(*,0), 
	"AnoMês" VARCHAR2(50), 
	"UF" VARCHAR2(50), 
	"Cidade" VARCHAR2(255), 
	"CO_MUNICIPIO" NUMBER(*,0), 
	"CanalEntrada" VARCHAR2(50), 
	"Condição" VARCHAR2(50), 
	"TipoAtendimento" VARCHAR2(50), 
	"Serviço" VARCHAR2(255), 
	"Marca" VARCHAR2(100), 
	"Assunto" VARCHAR2(100), 
	"Problema" VARCHAR2(255), 
	"Linha" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
